name: Build Seed Executable

on:
  push:                          # 🔔 build on every commit to main …
    branches: [ main ]
    tags:     [ "v*" ]           # … and also on any tag that starts with v

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]   # build Linux + Windows
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # --- extra dep so PyInstaller sees psutil ----
      - name: Install build deps
        run: pip install psutil

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile core/seed_bootstrap.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: seed-binaries-${{ matrix.os }}
          path: dist/seed_bootstrap*
