name: Build Seed Executable

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]   # 🆕 build on Linux *and* Windows
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies    # <— new step
        run: pip install psutil

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile core/seed_bootstrap.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Each OS gets its own ZIP: seed-binaries-ubuntu, seed-binaries-windows
          name: seed-binaries-${{ matrix.os }}
          path: |
            dist/seed_bootstrap*
