name: Build Seed Executable

on:
  push:                     # run on every push to main *and* on any v-tag
    branches: [ main ]
    tags:     [ "v*" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest   # 🎯 build only on Linux for now

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build deps          # psutil for env_detector
        run: pip install psutil

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --noconfirm --onefile core/seed_bootstrap.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: seed-binaries-linux
          path: dist/seed_bootstrap*
