name: Build Seed Executable (Windows)

on:
  push:
    tags: [ "v*" ]          # build only when you push a v-tag

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build exe with PyInstaller
        shell: bash          # use bash to avoid the PowerShell/debug prompt
        run: |
          pip install psutil pyinstaller
          pyinstaller --noconfirm --onefile core/seed_bootstrap.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: seed-binaries-windows
          path: dist/seed_bootstrap*.exe
