name: Build Seed Executable
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install pyinstaller
      - run: pyinstaller --onefile core/seed_bootstrap.py
      - uses: actions/upload-artifact@v4
        with: { name: seed-binaries, path: dist/seed_bootstrap* }